import json


from backend.app.llm.groq_provider import GroqProvider
from backend.app.models.workspace import Workspace


class CodeGenerator:

    def __init__(self):
        self.llm = GroqProvider()

    def generate_package_json(self) -> str:
        return """{
  "name": "genesis-generated-project",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-router-dom": "^7.0.0"
  },
  "devDependencies": {
    "@tailwindcss/postcss": "^4.0.0",
    "@vitejs/plugin-react": "^5.0.0",
    "autoprefixer": "^10.4.0",
    "postcss": "^8.5.0",
    "tailwindcss": "^4.0.0",
    "vite": "^7.0.0"
  }
}"""

    def generate_vite_config(self) -> str:
        return """import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
"""

    def generate_postcss_config(self) -> str:
        return """module.exports = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
"""

    def generate_tailwind_config(self) -> str:
        return """module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
"""

    def generate_index_html(self) -> str:
        return """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <meta
      name="description"
      content="Generated by Genesis"
    />
    <title>Genesis Website</title>
  </head>

  <body>
    <div id="root"></div>

    <script
      type="module"
      src="/src/main.jsx"
    ></script>
  </body>
</html>
"""

    def generate_index_css(self) -> str:
        return """@import "tailwindcss";

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  min-width: 320px;
  background: #ffffff;
  color: #111827;
  font-family:
    Inter,
    system-ui,
    -apple-system,
    BlinkMacSystemFont,
    "Segoe UI",
    sans-serif;
}

* {
  box-sizing: border-box;
}
"""

    def _clean_generated_code(
        self,
        code: str
    ) -> str:

        if not isinstance(code, str):
            raise ValueError(
                "Generated code must be a string."
            )

        code = code.strip()

        if code.startswith("```"):
            code = code.replace(
                "```jsx",
                "",
                1
            )

            code = code.replace(
                "```javascript",
                "",
                1
            )

            code = code.replace(
                "```js",
                "",
                1
            )

            code = code.replace(
                "```",
                "",
                1
            )

            code = code.strip()

        # Some LLM responses contain literal "\n"
        # characters instead of actual line breaks.
        code = code.replace(
            "\\\n",
            "\n"
        )

        return code

    def generate_main(self) -> str:
        return """import React from "react";
import ReactDOM from "react-dom/client";
import { RouterProvider } from "react-router-dom";

import router from "./router.jsx";
import "./index.css";

ReactDOM.createRoot(
  document.getElementById("root")
).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>
);
"""

    def generate_app(self) -> str:
        return """import React from "react";
import { Outlet } from "react-router-dom";

import Header from "./components/Header.jsx";
import Footer from "./components/Footer.jsx";

function App() {
  return (
    <div className="flex min-h-screen flex-col bg-white text-gray-900">
      <Header />

      <main className="flex-1">
        <Outlet />
      </main>

      <Footer />
    </div>
  );
}

export default App;
"""

    def generate_router(self) -> str:
        return """import {
  createBrowserRouter
} from "react-router-dom";

import App from "./App.jsx";
import Home from "./pages/Home.jsx";
import About from "./pages/About.jsx";
import Projects from "./pages/Projects.jsx";
import Contact from "./pages/Contact.jsx";

const router = createBrowserRouter([
  {
    path: "/",
    element: <App />,
    children: [
      {
        index: true,
        element: <Home />,
      },
      {
        path: "about",
        element: <About />,
      },
      {
        path: "projects",
        element: <Projects />,
      },
      {
        path: "contact",
        element: <Contact />,
      },
      {
        path: "*",
        element: <Home />,
      },
    ],
  },
]);

export default router;
"""

    def generate_file(
        self,
        workspace: Workspace,
        file_path: str
    ) -> str:

        # Deterministic infrastructure files.
        # These do not require an LLM call.

        if file_path == "package.json":
            return self.generate_package_json()

        if file_path == "vite.config.js":
            return self.generate_vite_config()

        if file_path == "postcss.config.cjs":
            return self.generate_postcss_config()

        if file_path == "tailwind.config.cjs":
            return self.generate_tailwind_config()

        if file_path == "index.html":
            return self.generate_index_html()

        if file_path == "src/index.css":
            return self.generate_index_css()

        if file_path == "src/main.jsx":
            return self.generate_main()

        if file_path == "src/App.jsx":
            return self.generate_app()

        if file_path == "src/router.jsx":
            return self.generate_router()

        available_files = self._get_available_files(
            workspace,
            file_path
        )

        relevant_files = self._get_relevant_files(
            workspace,
            file_path
        )

        context = ""

        if relevant_files:
            context = "\n\n".join(
                f"--- {path} ---\n{workspace.files[path]}"
                for path in relevant_files
                if path in workspace.files
            )

        prompt = f"""
You are an expert React, Vite, and Tailwind CSS developer.

Generate the source code for exactly ONE file.

PROJECT:

Framework:
{workspace.blueprint.framework}

Bundler:
{workspace.blueprint.bundler}

Styling:
{workspace.blueprint.styling}

Router:
{workspace.blueprint.router}

PAGES:

{", ".join(workspace.blueprint.pages)}

COMPONENTS:

{", ".join(workspace.blueprint.components)}

ALL AVAILABLE PROJECT FILES:

{available_files}

FILE TO GENERATE:

{file_path}

RELEVANT EXISTING FILES:

{context}

IMPORTANT RULES:

1. Generate ONLY the contents of the requested file.

2. Do not use Markdown code fences.

3. Do not explain anything.

4. Follow the React + Vite + Tailwind CSS architecture.

5. Use correct relative imports.

6. Keep the code clean and production-ready.

7. Keep this file consistent with the relevant existing files.

8. Do not generate any other files.

9. All imports must refer to packages or files that exist.

10. React projects must use React and React DOM correctly.

11. React Router must be used when routing is defined.

12. Do not introduce unnecessary dependencies.

13. Every imported npm package must exist in package.json.

14. Every local import must point to a file in the project.

15. Use JSX syntax for React components.

16. Use Tailwind CSS classes where appropriate.

17. Keep the application responsive.

18. Follow the pages and components defined in the blueprint.

19. Do not generate fake binary content for image files.

20. If the requested file is JavaScript, return valid JavaScript only.

21. If the requested file is JSX, return valid JSX only.

22. Do not include Markdown formatting.

23. Do not introduce a new npm package.

24. Preserve the project's existing technology choices.

25. Do not modify package dependencies.

26. Do not modify Vite, Tailwind, or PostCSS configuration.

27. Do not create configuration files.

28. Use existing files and components where appropriate.


GLOBAL APPLICATION ARCHITECTURE:

29. App.jsx is the global application shell.

30. App.jsx is responsible for rendering the global Header,
    Navigation, and Footer components.

31. Page components such as Home, About, Projects, and Contact
    must NOT import Header, Navigation, or Footer.

32. Page components must NOT render Header, Navigation, or Footer.

33. Page components should contain only their own page-specific
    content and sections.

34. Do not render the same global component more than once.

35. Do not create duplicate navigation bars.

36. Do not create duplicate footers.

37. Do not create a second application shell inside a page.

38. If a Layout component exists, it must not cause Header,
    Navigation, or Footer to be rendered a second time.

39. Pages must work correctly when rendered through the existing
    App.jsx and router.jsx structure.


JSX AND SOURCE CODE RULES:

40. Use normal JSX quotes such as className="..." and do not escape
    JSX attribute quotes with backslashes.

41. Never generate sequences such as className=\\"...\\"

42. Never import prop-types or any package that is not present in
    package.json.

43. Do not use PropTypes.

44. Do not use dependencies that are not already installed.

45. Do not intentionally output literal \\n text into JSX.

46. Use real line breaks between JSX elements.

47. Do not place escaped newline text such as "\\n" between
    visible JSX elements.

48. Component children must be rendered correctly.

49. If a component receives children, it must render {{children}}
    where appropriate.

50. Keep component props consistent with how other project files
    use the component.


RUNTIME COMPONENT CONTRACT RULES:

51. Never call .map(), .filter(), .forEach(), .reduce(), or similar
    array methods on a value that could be undefined or null.

52. Array props must use safe defaults such as:

    ({{ items = [] }})

    or equivalent null-safe logic.

53. Object props must use safe defaults when appropriate.

54. Never assume a required prop exists unless the parent component
    visibly provides that prop.

55. If a component requires data and there is no backend, API,
    database, or other data source in the project, provide sensible
    static fallback/demo data rather than leaving the data undefined.

56. If a parent renders a component that expects props, the parent
    must provide those props.

57. Keep prop names identical between component definitions and
    component usage.

58. Do not create a component that requires a prop and then render
    it without that prop.

59. Before returning the file, mentally verify every component usage
    in this file against the expected props of the imported component.

60. Components that render collections must remain functional even
    when their collection prop is omitted.

61. Prefer safe defaults over runtime crashes.

62. Do not access properties of potentially undefined objects without
    optional chaining, guards, or safe defaults.

63. Do not generate runtime code that assumes browser APIs or data
    exist when they may not exist.


BUTTON AND LINK CONTRACT:

64. If a Button component supports an href prop, it must render an
    appropriate anchor/link element when href is supplied.

65. If href is not supplied, Button should render a normal button.

66. Button must safely support common props such as:
    children, onClick, type, className, disabled, href, target, rel.

67. Components must use Button according to its actual supported props.

68. Do not pass href to a Button implementation that does not support it.


ASSET RULES:

69. Do not reference local images, fonts, or other assets unless
    the corresponding file exists in the project.

70. Do not invent paths such as /profile.jpg,
    /images/project.png, or /assets/image.jpg unless those files
    are actually present.

71. Do not create fake binary files.

72. Prefer CSS, gradients, icons, or text when no real asset exists.


Return ONLY the file contents.
"""

        response = self.llm.generate(
            prompt
        )

        if not response:
            raise ValueError(
                f"LLM returned an empty response "
                f"for {file_path}"
            )

        return self._clean_generated_code(
            response
        )

    def generate_batch(
        self,
        workspace: Workspace,
        file_paths: list[str]
    ) -> dict[str, str]:

        generated_files = {}

        print(
            f"\n=== GENERATING {len(file_paths)} FILE(S) "
            f"INDIVIDUALLY ==="
        )

        for index, file_path in enumerate(
            file_paths,
            start=1
        ):

            print(
                f"\n--- FILE {index}/{len(file_paths)} ---"
            )

            print(
                f"Generating: {file_path}"
            )

            last_error = None

            for attempt in range(1, 4):

                try:

                    code = self.generate_file(
                        workspace,
                        file_path
                    )

                    if not code or not code.strip():
                        raise ValueError(
                            "LLM returned empty code."
                        )

                    generated_files[file_path] = code

                    print(
                        f"Generated: {file_path}"
                    )

                    break

                except Exception as error:

                    last_error = error

                    print(
                        f"Generation failed for "
                        f"{file_path}"
                    )

                    print(
                        f"Attempt {attempt}/3"
                    )

                    print(
                        f"Error: {error}"
                    )

                    if attempt == 3:
                        raise RuntimeError(
                            f"Failed to generate "
                            f"'{file_path}' after "
                            f"3 attempts."
                        ) from error

            if file_path not in generated_files:
                raise RuntimeError(
                    f"File generation failed: "
                    f"{file_path}. "
                    f"Last error: {last_error}"
                )

            workspace.files[file_path] = (
                generated_files[file_path]
            )

        return generated_files

    def _get_available_files(
        self,
        workspace: Workspace,
        current_file: str
    ) -> str:

        paths = list(
            workspace.blueprint.files
        )

        if current_file not in paths:
            paths.append(current_file)

        return "\n".join(
            f"- {path}"
            for path in paths
        )

    def _get_relevant_files(
        self,
        workspace: Workspace,
        current_file: str
    ) -> list[str]:

        relevant = []

        if current_file.startswith(
            "src/components/"
        ):

            priority = [
                "src/App.jsx",
                "src/router.jsx",
                "src/index.css",
            ]

            for path in priority:
                if path in workspace.files:
                    relevant.append(path)

        elif current_file.startswith(
            "src/pages/"
        ):

            priority = [
                "src/App.jsx",
                "src/router.jsx",
            ]

            for path in priority:
                if path in workspace.files:
                    relevant.append(path)

            component_files = [
                path
                for path in workspace.files
                if path.startswith(
                    "src/components/"
                )
            ]

            relevant.extend(
                component_files
            )

        elif current_file == "src/App.jsx":

            component_files = [
                path
                for path in workspace.files
                if path.startswith(
                    "src/components/"
                )
            ]

            relevant.extend(
                component_files
            )

        return relevant